
export type ServiceCategory = "Clipboard" | "Client Tools" | "Security" | "AI" | "Barcode" | "Developer" | "Packaging" | "Storage";

export interface ProductionService {
  id: string;
  displayName: string;
  title: string;
  category: string;
  status: ServiceStatus;
  runtimeType: string;
  tier: "live" | "guarded" | "planned";
  dependency: string;
  implemented: boolean;
  requiresConfig: boolean;
  userFallback: string;
  fallback: string;
  actionHandler: string;
  description: string;
  channel: string;
}

// Production services catalog - matches serviceOperations.ts capabilities
export const PRODUCTION_SERVICES: ProductionService[] = [
  // Clipboard Core Services
  {
    id: "smart-clipboard-inbox",
    displayName: "Smart Clipboard Inbox",
    title: "Smart Clipboard Inbox",
    category: "Clipboard",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Group clips by date for organized viewing.",
    fallback: "Group clips by date for organized viewing.",
    actionHandler: "group",
    description: "Groups clipboard items by date for organized viewing and analysis.",
    channel: "group",
  },
  {
    id: "windows-current-clipboard-import",
    displayName: "Current Clipboard Import",
    title: "Current Clipboard Import",
    category: "Clipboard",
    status: "Ready",
    runtimeType: "browser-clipboard",
    tier: "live",
    dependency: "Clipboard API",
    implemented: true,
    requiresConfig: false,
    userFallback: "Requires browser clipboard permission.",
    fallback: "Requires browser clipboard permission.",
    actionHandler: "read-clipboard",
    description: "Imports current clipboard content into the KNOUX workspace.",
    channel: "read-clipboard",
  },
  {
    id: "windows-live-clipboard-monitor",
    displayName: "Live Clipboard Monitor",
    title: "Live Clipboard Monitor",
    category: "Clipboard",
    status: "Guarded",
    runtimeType: "electron-bridge",
    tier: "guarded",
    dependency: "Electron IPC",
    implemented: false,
    requiresConfig: false,
    userFallback: "Live monitor requires verified Electron bridge. Web runtime is guarded.",
    fallback: "Live monitor requires verified Electron bridge. Web runtime is guarded.",
    actionHandler: "monitor",
    description: "Monitors clipboard changes in real-time. Requires Electron runtime.",
    channel: "monitor",
  },
  {
    id: "persistent-local-clipboard-vault",
    displayName: "Local Clipboard Vault",
    title: "Local Clipboard Vault",
    category: "Clipboard",
    status: "Active",
    runtimeType: "local-storage",
    tier: "live",
    dependency: "localStorage",
    implemented: true,
    requiresConfig: false,
    userFallback: "Local storage health check available.",
    fallback: "Local storage health check available.",
    actionHandler: "health",
    description: "Audits local clipboard vault storage health and usage.",
    channel: "health",
  },
  {
    id: "large-history-storage",
    displayName: "Large History Storage",
    title: "Large History Storage",
    category: "Clipboard",
    status: "Ready",
    runtimeType: "local-storage",
    tier: "live",
    dependency: "localStorage",
    implemented: true,
    requiresConfig: false,
    userFallback: "Storage retention limits configurable in settings.",
    fallback: "Storage retention limits configurable in settings.",
    actionHandler: "retention",
    description: "Manages large clipboard history with configurable retention limits.",
    channel: "retention",
  },
  {
    id: "clipboard-deduplication",
    displayName: "Clipboard Deduplication",
    title: "Clipboard Deduplication",
    category: "Clipboard",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Duplicate detection and cleanup available.",
    fallback: "Duplicate detection and cleanup available.",
    actionHandler: "dedupe-preview",
    description: "Detects and removes duplicate clipboard entries to save storage.",
    channel: "dedupe-preview",
  },
  {
    id: "quick-paste-favorites",
    displayName: "Quick Paste Favorites",
    title: "Quick Paste Favorites",
    category: "Clipboard",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Favorite items are available for quick access.",
    fallback: "Favorite items are available for quick access.",
    actionHandler: "favorites",
    description: "Lists and provides quick access to favorited clipboard items.",
    channel: "favorites",
  },
  {
    id: "clipboard-collections",
    displayName: "Clipboard Collections",
    title: "Clipboard Collections",
    category: "Clipboard",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Organize clips into folders and collections.",
    fallback: "Organize clips into folders and collections.",
    actionHandler: "collections",
    description: "Organizes clipboard items into folders and collections.",
    channel: "collections",
  },
  // Client Tools
  {
    id: "smart-labels-auto-tags",
    displayName: "Smart Auto-Tagging",
    title: "Smart Auto-Tagging",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Automatic content tagging available.",
    fallback: "Automatic content tagging available.",
    actionHandler: "tags",
    description: "Automatically generates tags for clipboard content based on analysis.",
    channel: "tags",
  },
  {
    id: "clipboard-backup-export",
    displayName: "JSON Backup Export",
    title: "JSON Backup Export",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Export clipboard history as JSON.",
    fallback: "Export clipboard history as JSON.",
    actionHandler: "download-json",
    description: "Exports clipboard history as a JSON backup file.",
    channel: "download-json",
  },
  {
    id: "json-export",
    displayName: "JSON Export",
    title: "JSON Export",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Export clipboard data as JSON.",
    fallback: "Export clipboard data as JSON.",
    actionHandler: "download-json",
    description: "Exports clipboard data as a JSON file for backup or sharing.",
    channel: "download-json",
  },
  {
    id: "csv-export",
    displayName: "CSV Export",
    title: "CSV Export",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Export clipboard data as CSV.",
    fallback: "Export clipboard data as CSV.",
    actionHandler: "download-csv",
    description: "Exports clipboard data as a CSV file for spreadsheet analysis.",
    channel: "download-csv",
  },
  {
    id: "clipboard-backup-restore",
    displayName: "Backup Restore",
    title: "Backup Restore",
    category: "Client Tools",
    status: "Ready",
    runtimeType: "local",
    tier: "live",
    dependency: "JSON file",
    implemented: true,
    requiresConfig: false,
    userFallback: "Restore from JSON backup in Preferences.",
    fallback: "Restore from JSON backup in Preferences.",
    actionHandler: "open-settings",
    description: "Restores clipboard history from a validated JSON backup file.",
    channel: "open-settings",
  },
  {
    id: "smart-search-assistant",
    displayName: "Smart Search",
    title: "Smart Search",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Search clipboard content by keywords.",
    fallback: "Search clipboard content by keywords.",
    actionHandler: "search",
    description: "Searches clipboard history by keywords and content.",
    channel: "search",
  },
  {
    id: "daily-clipboard-summary",
    displayName: "Daily Summary",
    title: "Daily Summary",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate daily clipboard activity summary.",
    fallback: "Generate daily clipboard activity summary.",
    actionHandler: "daily-summary",
    description: "Generates a daily summary of clipboard activity and usage.",
    channel: "daily-summary",
  },
  {
    id: "auto-cleanup",
    displayName: "Auto Cleanup",
    title: "Auto Cleanup",
    category: "Client Tools",
    status: "Ready",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Compact and optimize local storage.",
    fallback: "Compact and optimize local storage.",
    actionHandler: "compact",
    description: "Compacts and optimizes local clipboard storage for efficiency.",
    channel: "compact",
  },
  {
    id: "web-clipboard-limited-mode",
    displayName: "Web Clipboard Write",
    title: "Web Clipboard Write",
    category: "Client Tools",
    status: "Ready",
    runtimeType: "browser-clipboard",
    tier: "live",
    dependency: "Clipboard API",
    implemented: true,
    requiresConfig: false,
    userFallback: "Requires browser clipboard permission.",
    fallback: "Requires browser clipboard permission.",
    actionHandler: "write-clipboard",
    description: "Writes text to browser clipboard. Requires permission.",
    channel: "write-clipboard",
  },
  {
    id: "start-on-login-status",
    displayName: "Start on Login",
    title: "Start on Login",
    category: "Client Tools",
    status: "Guarded",
    runtimeType: "electron-native",
    tier: "guarded",
    dependency: "Electron",
    implemented: false,
    requiresConfig: false,
    userFallback: "Native startup control requires Electron installer.",
    fallback: "Native startup control requires Electron installer.",
    actionHandler: "startup-boundary",
    description: "Controls app startup behavior. Requires Electron runtime.",
    channel: "startup-boundary",
  },
  {
    id: "current-session-import",
    displayName: "Session Import",
    title: "Session Import",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Import current session text.",
    fallback: "Import current session text.",
    actionHandler: "session-import",
    description: "Imports text from the current session into clipboard history.",
    channel: "session-import",
  },
  {
    id: "smart-text-cleaner",
    displayName: "Text Cleaner",
    title: "Text Cleaner",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Clean and normalize text content.",
    fallback: "Clean and normalize text content.",
    actionHandler: "clean",
    description: "Cleans and normalizes text content by removing extra whitespace.",
    channel: "clean",
  },
  {
    id: "link-organizer",
    displayName: "Link Organizer",
    title: "Link Organizer",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Extract and organize URLs from content.",
    fallback: "Extract and organize URLs from content.",
    actionHandler: "links",
    description: "Extracts and organizes URLs from clipboard content.",
    channel: "links",
  },
  {
    id: "code-snippet-saver",
    displayName: "Code Snippet Saver",
    title: "Code Snippet Saver",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Detect and save code snippets.",
    fallback: "Detect and save code snippets.",
    actionHandler: "code-detect",
    description: "Detects code snippets and saves them with proper formatting.",
    channel: "code-detect",
  },
  {
    id: "entity-extractor",
    displayName: "Entity Extractor",
    title: "Entity Extractor",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Extract entities like emails, phones, URLs.",
    fallback: "Extract entities like emails, phones, URLs.",
    actionHandler: "entities",
    description: "Extracts entities like emails, phone numbers, and URLs from text.",
    channel: "entities",
  },
  {
    id: "one-click-copy-templates",
    displayName: "Copy Templates",
    title: "Copy Templates",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Templates available in Clipboard Hub.",
    fallback: "Templates available in Clipboard Hub.",
    actionHandler: "templates",
    description: "Provides one-click copy templates for common text patterns.",
    channel: "templates",
  },
  {
    id: "business-mode-presets",
    displayName: "Business Presets",
    title: "Business Presets",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Presets for different business use cases.",
    fallback: "Presets for different business use cases.",
    actionHandler: "presets",
    description: "Provides presets for different business use cases and workflows.",
    channel: "presets",
  },
  {
    id: "workflow-quick-actions",
    displayName: "Workflow Actions",
    title: "Workflow Actions",
    category: "Client Tools",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Quick workflow controls for clipboard management.",
    fallback: "Quick workflow controls for clipboard management.",
    actionHandler: "workflow",
    description: "Provides quick workflow controls for clipboard management.",
    channel: "workflow",
  },
  {
    id: "offline-mode-indicator",
    displayName: "Offline Indicator",
    title: "Offline Indicator",
    category: "Client Tools",
    status: "Active",
    runtimeType: "browser",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Check online/offline runtime status.",
    fallback: "Check online/offline runtime status.",
    actionHandler: "runtime",
    description: "Indicates whether the app is running in online or offline mode.",
    channel: "runtime",
  },
  // Security Services
  {
    id: "sensitive-data-guard",
    displayName: "Sensitive Data Guard",
    title: "Sensitive Data Guard",
    category: "Security",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Scans for sensitive data patterns.",
    fallback: "Scans for sensitive data patterns.",
    actionHandler: "guard-scan",
    description: "Scans content for sensitive data patterns like passwords and API keys.",
    channel: "guard-scan",
  },
  {
    id: "secrets-exposure-guard",
    displayName: "Secrets Exposure Guard",
    title: "Secrets Exposure Guard",
    category: "Security",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Detects exposed secrets and credentials.",
    fallback: "Detects exposed secrets and credentials.",
    actionHandler: "guard-scan",
    description: "Detects exposed secrets and credentials in clipboard content.",
    channel: "guard-scan",
  },
  {
    id: "local-privacy-guard",
    displayName: "Privacy Guard",
    title: "Privacy Guard",
    category: "Security",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Records privacy guard check locally.",
    fallback: "Records privacy guard check locally.",
    actionHandler: "privacy",
    description: "Records privacy guard checks for new clipboard items.",
    channel: "privacy",
  },
  {
    id: "vault-encryption",
    displayName: "Vault Encryption",
    title: "Vault Encryption",
    category: "Security",
    status: "Guarded",
    runtimeType: "electron-bridge",
    tier: "guarded",
    dependency: "Electron IPC",
    implemented: false,
    requiresConfig: false,
    userFallback: "Electron encryption bridge required for full encryption.",
    fallback: "Electron encryption bridge required for full encryption.",
    actionHandler: "encryption-check",
    description: "Checks encryption status. Full encryption requires Electron runtime.",
    channel: "encryption-check",
  },
  {
    id: "cloud-sync-boundary",
    displayName: "Cloud Sync Boundary",
    title: "Cloud Sync Boundary",
    category: "Security",
    status: "Guarded",
    runtimeType: "local-first",
    tier: "guarded",
    dependency: "None",
    implemented: false,
    requiresConfig: false,
    userFallback: "Cloud sync is intentionally blocked in local-first build.",
    fallback: "Cloud sync is intentionally blocked in local-first build.",
    actionHandler: "sync-boundary",
    description: "Blocks cloud sync to maintain local-first security posture.",
    channel: "sync-boundary",
  },
  {
    id: "ai-upload-guard",
    displayName: "AI Upload Guard",
    title: "AI Upload Guard",
    category: "Security",
    status: "Guarded",
    runtimeType: "local",
    tier: "guarded",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Guards AI uploads for sensitive content.",
    fallback: "Guards AI uploads for sensitive content.",
    actionHandler: "ai-guard",
    description: "Guards AI uploads by detecting sensitive content before transmission.",
    channel: "ai-guard",
  },
  {
    id: "redaction-lab",
    displayName: "Redaction Lab",
    title: "Redaction Lab",
    category: "Security",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Redact sensitive patterns from text.",
    fallback: "Redact sensitive patterns from text.",
    actionHandler: "redact",
    description: "Redacts sensitive patterns like passwords and keys from text.",
    channel: "redact",
  },
  {
    id: "security-audit-trail",
    displayName: "Security Audit Trail",
    title: "Security Audit Trail",
    category: "Security",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate security audit markers.",
    fallback: "Generate security audit markers.",
    actionHandler: "security-audit",
    description: "Generates security audit markers for clipboard operations.",
    channel: "security-audit",
  },
  // AI Services
  {
    id: "openrouter-live-ai",
    displayName: "OpenRouter AI",
    title: "OpenRouter AI",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "chat",
    description: "General AI chat powered by OpenRouter. Requires API configuration.",
    channel: "chat",
  },
  {
    id: "customer-reply-builder",
    displayName: "Customer Reply Builder",
    title: "Customer Reply Builder",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "reply",
    description: "Builds customer service replies using AI. Requires API configuration.",
    channel: "reply",
  },
  {
    id: "summarize-clip",
    displayName: "AI Summarization",
    title: "AI Summarization",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "summarize",
    description: "Summarizes clipboard content using AI. Requires API configuration.",
    channel: "summarize",
  },
  {
    id: "rewrite-clip",
    displayName: "AI Rewrite",
    title: "AI Rewrite",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "rewrite",
    description: "Rewrites clipboard content using AI. Requires API configuration.",
    channel: "rewrite",
  },
  {
    id: "translate-clip",
    displayName: "AI Translation",
    title: "AI Translation",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "translate",
    description: "Translates clipboard content using AI. Requires API configuration.",
    channel: "translate",
  },
  {
    id: "analyze-clip",
    displayName: "AI Analysis",
    title: "AI Analysis",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "analyze",
    description: "Analyzes clipboard content using AI. Requires API configuration.",
    channel: "analyze",
  },
  {
    id: "format-clip",
    displayName: "AI Formatting",
    title: "AI Formatting",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "format",
    description: "Formats clipboard content using AI. Requires API configuration.",
    channel: "format",
  },
  {
    id: "explain-code-clip",
    displayName: "AI Code Explanation",
    title: "AI Code Explanation",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "explain-code",
    description: "Explains code snippets using AI. Requires API configuration.",
    channel: "explain-code",
  },
  {
    id: "commit-message",
    displayName: "AI Commit Messages",
    title: "AI Commit Messages",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "commit-message",
    description: "Generates Git commit messages using AI. Requires API configuration.",
    channel: "commit-message",
  },
  {
    id: "readme-block",
    displayName: "AI README Generator",
    title: "AI README Generator",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "readme-block",
    description: "Generates README documentation using AI. Requires API configuration.",
    channel: "readme-block",
  },
  {
    id: "api-docs",
    displayName: "AI API Documentation",
    title: "AI API Documentation",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "api-docs",
    description: "Generates API documentation using AI. Requires API configuration.",
    channel: "api-docs",
  },
  {
    id: "action-items",
    displayName: "AI Action Items",
    title: "AI Action Items",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "action-items",
    description: "Extracts action items from text using AI. Requires API configuration.",
    channel: "action-items",
  },
  {
    id: "checklist",
    displayName: "AI Checklist Generator",
    title: "AI Checklist Generator",
    category: "AI",
    status: "Ready",
    runtimeType: "server-route",
    tier: "live",
    dependency: "OpenRouter",
    implemented: true,
    requiresConfig: true,
    userFallback: "AI provider must be configured in settings.",
    fallback: "AI provider must be configured in settings.",
    actionHandler: "checklist",
    description: "Generates checklists from text using AI. Requires API configuration.",
    channel: "checklist",
  },
  {
    id: "offline-ai-boundary",
    displayName: "Offline AI Boundary",
    title: "Offline AI Boundary",
    category: "AI",
    status: "Guarded",
    runtimeType: "local",
    tier: "guarded",
    dependency: "None",
    implemented: false,
    requiresConfig: false,
    userFallback: "Offline generation is not faked. Configure OpenRouter for real AI.",
    fallback: "Offline generation is not faked. Configure OpenRouter for real AI.",
    actionHandler: "offline-boundary",
    description: "Offline AI generation is not supported. Requires OpenRouter configuration.",
    channel: "offline-boundary",
  },
  // Barcode Services
  {
    id: "camera-scan",
    displayName: "Camera Scan",
    title: "Camera Scan",
    category: "Barcode",
    status: "Guarded",
    runtimeType: "browser-camera",
    tier: "guarded",
    dependency: "Camera API",
    implemented: true,
    requiresConfig: false,
    userFallback: "Available on Barcode Scanner page. Requires camera permission.",
    fallback: "Available on Barcode Scanner page. Requires camera permission.",
    actionHandler: "open-barcode",
    description: "Scans barcodes using device camera. Available on Barcode Scanner page.",
    channel: "open-barcode",
  },
  {
    id: "image-upload-scan",
    displayName: "Image Upload Scan",
    title: "Image Upload Scan",
    category: "Barcode",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Upload barcode images for scanning.",
    fallback: "Upload barcode images for scanning.",
    actionHandler: "open-barcode",
    description: "Scans barcodes from uploaded images. Available on Barcode Scanner page.",
    channel: "open-barcode",
  },
  {
    id: "clipboard-image-scan",
    displayName: "Clipboard Image Scan",
    title: "Clipboard Image Scan",
    category: "Barcode",
    status: "Guarded",
    runtimeType: "clipboard-image",
    tier: "guarded",
    dependency: "Clipboard API",
    implemented: true,
    requiresConfig: false,
    userFallback: "Scan barcodes from clipboard images.",
    fallback: "Scan barcodes from clipboard images.",
    actionHandler: "open-barcode",
    description: "Scans barcodes from clipboard images. Available on Barcode Scanner page.",
    channel: "open-barcode",
  },
  {
    id: "manual-paste-decode",
    displayName: "Manual Paste Decode",
    title: "Manual Paste Decode",
    category: "Barcode",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Paste barcode text for decoding.",
    fallback: "Paste barcode text for decoding.",
    actionHandler: "open-barcode",
    description: "Decodes barcodes from manually pasted text. Available on Barcode Scanner page.",
    channel: "open-barcode",
  },
  {
    id: "save-barcode-result",
    displayName: "Save Barcode Result",
    title: "Save Barcode Result",
    category: "Barcode",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Save barcode scan results to clipboard.",
    fallback: "Save barcode scan results to clipboard.",
    actionHandler: "open-barcode",
    description: "Saves barcode scan results to clipboard history.",
    channel: "open-barcode",
  },
  {
    id: "barcode-extract-from-clipboard",
    displayName: "Barcode Extract",
    title: "Barcode Extract",
    category: "Barcode",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Extract barcode patterns from clipboard.",
    fallback: "Extract barcode patterns from clipboard.",
    actionHandler: "open-barcode",
    description: "Extracts barcode patterns from clipboard content.",
    channel: "open-barcode",
  },
  // Developer Tools (subset - more in developerTools.ts)
  {
    id: "json-format",
    displayName: "JSON Formatter",
    title: "JSON Formatter",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Format and validate JSON content.",
    fallback: "Format and validate JSON content.",
    actionHandler: "json-format",
    description: "Formats and validates JSON content with proper indentation.",
    channel: "json-format",
  },
  {
    id: "regex-test",
    displayName: "Regex Tester",
    title: "Regex Tester",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Test regular expressions against text.",
    fallback: "Test regular expressions against text.",
    actionHandler: "regex-test",
    description: "Tests regular expressions against text input.",
    channel: "regex-test",
  },
  {
    id: "markdown-table",
    displayName: "Markdown Table",
    title: "Markdown Table",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Convert data to Markdown tables.",
    fallback: "Convert data to Markdown tables.",
    actionHandler: "markdown-table",
    description: "Converts data to Markdown table format.",
    channel: "markdown-table",
  },
  {
    id: "env-checklist",
    displayName: ".env Checklist",
    title: ".env Checklist",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate .env file templates.",
    fallback: "Generate .env file templates.",
    actionHandler: "env-checklist",
    description: "Generates .env file templates and checklists.",
    channel: "env-checklist",
  },
  {
    id: "api-action",
    displayName: "API Request Template",
    title: "API Request Template",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate API request templates.",
    fallback: "Generate API request templates.",
    actionHandler: "api-action",
    description: "Generates API request templates for common operations.",
    channel: "api-action",
  },
  {
    id: "jwt-inspector",
    displayName: "JWT Inspector",
    title: "JWT Inspector",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Decode and inspect JWT tokens locally.",
    fallback: "Decode and inspect JWT tokens locally.",
    actionHandler: "jwt-inspector",
    description: "Decodes and inspects JWT tokens locally without verification.",
    channel: "jwt-inspector",
  },
  {
    id: "url-parser",
    displayName: "URL Parser",
    title: "URL Parser",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Parse and analyze URL components.",
    fallback: "Parse and analyze URL components.",
    actionHandler: "url-parser",
    description: "Parses and analyzes URL components and parameters.",
    channel: "url-parser",
  },
  {
    id: "diff-summary",
    displayName: "Diff Viewer",
    title: "Diff Viewer",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Compare text differences.",
    fallback: "Compare text differences.",
    actionHandler: "diff-summary",
    description: "Compares text differences and shows a diff summary.",
    channel: "diff-summary",
  },
  {
    id: "typescript-interface",
    displayName: "TypeScript Interface",
    title: "TypeScript Interface",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate TypeScript interfaces from JSON.",
    fallback: "Generate TypeScript interfaces from JSON.",
    actionHandler: "typescript-interface",
    description: "Generates TypeScript interfaces from JSON objects.",
    channel: "typescript-interface",
  },
  {
    id: "zod-schema",
    displayName: "Zod Schema Generator",
    title: "Zod Schema Generator",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate Zod schemas from TypeScript.",
    fallback: "Generate Zod schemas from TypeScript.",
    actionHandler: "zod-schema",
    description: "Generates Zod validation schemas from TypeScript types.",
    channel: "zod-schema",
  },
  {
    id: "sql-checklist",
    displayName: "SQL Checklist",
    title: "SQL Checklist",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate SQL query checklists.",
    fallback: "Generate SQL query checklists.",
    actionHandler: "sql-checklist",
    description: "Generates SQL query checklists and best practices.",
    channel: "sql-checklist",
  },
  {
    id: "release-notes",
    displayName: "Release Notes Generator",
    title: "Release Notes Generator",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate release notes from changes.",
    fallback: "Generate release notes from changes.",
    actionHandler: "release-notes",
    description: "Generates release notes from change descriptions.",
    channel: "release-notes",
  },
  {
    id: "bug-report",
    displayName: "Bug Report Generator",
    title: "Bug Report Generator",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate structured bug reports.",
    fallback: "Generate structured bug reports.",
    actionHandler: "bug-report",
    description: "Generates structured bug reports from issue descriptions.",
    channel: "bug-report",
  },
  {
    id: "test-plan",
    displayName: "Test Plan Generator",
    title: "Test Plan Generator",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate test plans from requirements.",
    fallback: "Generate test plans from requirements.",
    actionHandler: "test-plan",
    description: "Generates test plans from requirement descriptions.",
    channel: "test-plan",
  },
  {
    id: "i18n-audit",
    displayName: "i18n Audit",
    title: "i18n Audit",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Audit internationalization coverage.",
    fallback: "Audit internationalization coverage.",
    actionHandler: "i18n-audit",
    description: "Audits internationalization coverage and missing translations.",
    channel: "i18n-audit",
  },
  {
    id: "redaction-map",
    displayName: "Redaction Map",
    title: "Redaction Map",
    category: "Developer",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "None",
    implemented: true,
    requiresConfig: false,
    userFallback: "Generate redaction maps for sensitive data.",
    fallback: "Generate redaction maps for sensitive data.",
    actionHandler: "redaction-map",
    description: "Generates redaction maps for sensitive data patterns.",
    channel: "redaction-map",
  },
  // Packaging
  {
    id: "packaging-build",
    displayName: "Build Packaging",
    title: "Build Packaging",
    category: "Packaging",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "Node.js",
    implemented: true,
    requiresConfig: false,
    userFallback: "Run npm run build:renderer && npm run build:main",
    fallback: "Run npm run build:renderer && npm run build:main",
    actionHandler: "packaging",
    description: "Builds the renderer and main process for packaging.",
    channel: "packaging",
  },
  {
    id: "packaging-installer",
    displayName: "Installer Packaging",
    title: "Installer Packaging",
    category: "Packaging",
    status: "Active",
    runtimeType: "local",
    tier: "live",
    dependency: "Node.js",
    implemented: true,
    requiresConfig: false,
    userFallback: "Run npm run dist:installer",
    fallback: "Run npm run dist:installer",
    actionHandler: "packaging",
    description: "Packages the application as a Windows installer.",
    channel: "packaging",
  },
  // Storage
  {
    id: "sqlite-persistence-layer",
    displayName: "SQLite Persistence Layer",
    title: "SQLite Persistence Layer",
    category: "Storage",
    status: "Active",
    runtimeType: "electron-native",
    tier: "live",
    dependency: "SQLite3",
    implemented: true,
    requiresConfig: false,
    userFallback: "Database operations are handled by the main process.",
    fallback: "Database operations are handled by the main process.",
    actionHandler: "db-status",
    description: "Provides persistent storage for clipboard items and settings via SQLite.",
    channel: "db-status",
  },
];

const getCategoryReadinessPercent = (category: ServiceCategory) => {
  const categoryServices = PRODUCTION_SERVICES.filter(s => s.category === category);
  const total = categoryServices.length;
  if (total === 0) return 0;

  const active = categoryServices.filter(s => s.status === "Active").length;
  const ready = categoryServices.filter(s => s.status === "Ready").length;
  const guarded = categoryServices.filter(s => s.status === "Guarded").length;

  const weightedScore = (active * 100) + (ready * 75) + (guarded * 50);
  const maxScore = total * 100;

  return maxScore > 0 ? Math.round((weightedScore / maxScore) * 100) : 0;
};

export const getServiceReadinessPercent = () => {
  const total = PRODUCTION_SERVICES.length;
  if (total === 0) return 0;
  const active = PRODUCTION_SERVICES.filter(s => s.status === "Active").length;
  const ready = PRODUCTION_SERVICES.filter(s => s.status === "Ready").length;
  const guarded = PRODUCTION_SERVICES.filter(s => s.status === "Guarded").length;
  // Active = 100%, Ready = 75%, Guarded = 50%, Planned/Disabled/Missing = 0%
  const weightedScore = (active * 100) + (ready * 75) + (guarded * 50);
  const maxScore = total * 100;
  return maxScore > 0 ? Math.round((weightedScore / maxScore) * 100) : 0;
};

export const PRODUCTION_SCORE = {
  score: getServiceReadinessPercent(),
  securityVault: getCategoryReadinessPercent("Security"),
  openRouterBridge: getCategoryReadinessPercent("AI"),
  sqlitePersistence: getCategoryReadinessPercent("Storage"),
  serviceTransparency: Math.round(PRODUCTION_SERVICES.filter(s => s.userFallback && s.fallback).length / PRODUCTION_SERVICES.length * 100),
  label: "Active",
  status: "active",
  note: "Production score computed from real service statuses."
} as const;
